### ISSUE TITLE
ESP32 compilation error

### ISSUE THREAD

**Issue by ikkesia** [kdschlosser/lvgl_micropython#68]
`python make.py esp32 clean submodules mpy_cross BOARD=ESP32_GENERIC  DISPLAY=ili9341 INDEV=xpt2046`

```
/Users/tbe/esp/lvgl_micropython/lib/micropython/ports/esp32/machine_hw_spi.c: In function 'machine_hw_spi_bus_initilize':
/Users/tbe/esp/lvgl_micropython/lib/micropython/ports/esp32/machine_hw_spi.c:465:9: error: 'self' undeclared (first use in this function)
465 |     if (self->host == SPI2_HOST) {
|         ^~~~
/Users/tbe/esp/lvgl_micropython/lib/micropython/ports/esp32/machine_hw_spi.c:465:9: note: each undeclared identifier is reported only once for each function it appears in
[1295/1890] Building C object esp-idf/main_esp32/CMakeFiles/__idf_main_esp32.dir/Users/tbe/esp/lvgl_micropython/lib/micropython/lib/littlefs/lfs2.c.obj
ninja: build stopped: subcommand failed.

```

**Comment by kdschlosser** [comment]
https://github.com/kdschlosser/lvgl_micropython/discussions/69

**Comment by ikkesia** [comment]
Fixing machine_hw_spi.c locally

`465 | if (self->host == SPI2_HOST) {`
in
`465 | if (bus>host == SPI2_HOST) {`

the compilation proceeds without errors until
```
- Part 'factory' 0/0 @ 0x10000 size 0x267000 (overflow 0x72d0)
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /Users/tbe/esp/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC/log/idf_py_stderr_output_71243 and /Users/tbe/esp/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC/log/idf_py_stdout_output_71243
-e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
make: *** [all] Error 1


***** Resizing Partition *****

***** Running build again *****

Traceback (most recent call last):
  File "/Users/tbe/esp/lvgl_micropython/make.py", line 230, in <module>
    mod.compile(*extra_args)
  File "/Users/tbe/esp/lvgl_micropython/builder/esp32.py", line 957, in compile
    ret_code, output = spawn(cmds, env=env, cmpl=True)
  File "/Users/tbe/esp/lvgl_micropython/builder/__init__.py", line 450, in spawn
    if isinstance(cmd_[0], str):
IndexError: list index out of range

```
to get around this error I added the partition size (0x26f000) in the command line
--partition-size=2551808
`python make.py esp32 clean submodules mpy_cross --partition-size=2551808 BOARD=ESP32_GENERIC  DISPLAY=ili9341 INDEV=xpt2046`

to finally have a complete building.
